spring:
  http:
    multipart:
      max-file-size: 25MB
      max-request-size: 30MB
security:
  basic:
    enabled: false
  oauth2:
    resource:
      filter-order: 3          
videostat:
  ffprobe-path: ffprobe
  supported-formats:
  - video/x-flv
  - video/mp4
  - application/x-mpegURL
  - video/MP2T
  - video/3gpp
  - video/quicktime
  - video/x-msvideo
  - video/x-ms-wmv
  - video/x-matroska